### ISSUE TITLE
StatusMessage:This blob is being used by the system

### ISSUE THREAD

**Issue by ccic** [Azure/azure-storage-java#107]
I want to invoke CloudPageBlob's method "downloadPageRanges" to calculate the storage usage of VM, but there is exception raised:

Exception in thread "main" com.microsoft.azure.storage.StorageException: This blob is being used by the system.
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:89)
	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:305)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:175)
	at com.microsoft.azure.storage.blob.CloudPageBlob.downloadPageRanges(CloudPageBlob.java:506)
	at com.microsoft.azure.storage.blob.CloudPageBlob.downloadPageRanges(CloudPageBlob.java:463)
	at net.local.test.AccessStorage.main(AccessStorage.java:53)

I found if I stop the VM, the exception will disappear, and I can get the result. I want to know how to avoid the issue of "This blob is being used by the system" without stopping VM.

**Comment by pemari-msft** [comment]
Please take a snapshot of the blob and then download page ranges of the snapshot. This is by design - otherwise you'd have concurrency issues.
