### ISSUE TITLE
Backward compatibility for HDInsight for spark

### ISSUE THREAD

**Issue by NihalBhagchandani** [Azure/azure-storage-java#113]
by default HDInsight use classic implementation of azure-storage(azure-storage-2.2.0.jar) where it internally uses **CloudBlob.startCopyFromBlob** method, which has been removed in this latest version. 
due to this missing method in latest/current class if we use latest version in our spark application we get following error **Exception in thread "main" java.lang.NoSuchMethodError: com.microsoft.azure.storage.blob.CloudBlockBlob.startCopy(Ljava/net/URI;)Ljava/lang/String;**

**Comment by pemari-msft** [comment]
We follow semantic versioning scheme in our client libraries. We promise backwards compatibility only between minor versions and not major versions of our library. When there is a major version, the expectation is that the consumer make any adjustments to their code to handle breaking changes and recompile.

**Comment by dzlab** [comment]
I'm having this same issue with a local spark cluster
```
Caused by: java.lang.NoSuchMethodError: com.microsoft.azure.storage.blob.CloudBlob.startCopyFromBlob(Ljava/net/URI;Lcom/microsoft/azure/storage/AccessCondition;Lcom/microsoft/azure/storage/AccessCondition;Lcom/microsoft/azure/storage/blob/BlobRequestOptions;Lcom/microsoft/azure/storage/OperationContext;)Ljava/lang/String;
	at org.apache.hadoop.fs.azure.StorageInterfaceImpl$CloudBlobWrapperImpl.startCopyFromBlob(StorageInterfaceImpl.java:399)
	at org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.rename(AzureNativeFileSystemStore.java:2449)
	at org.apache.hadoop.fs.azure.AzureNativeFileSystemStore.rename(AzureNativeFileSystemStore.java:2372)
	at org.apache.hadoop.fs.azure.NativeAzureFileSystem$NativeAzureFsOutputStream.restoreKey(NativeAzureFileSystem.java:918)
	at org.apache.hadoop.fs.azure.NativeAzureFileSystem$NativeAzureFsOutputStream.close(NativeAzureFileSystem.java:819)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
	at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:320)
	at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
	at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
	at com.univocity.parsers.common.AbstractWriter.close(AbstractWriter.java:876)
	... 18 more
```
This is my dependencies:
```
  "com.azure" % "azure-storage-blob" % "12.0.0",
  "com.microsoft.azure" % "azure-storage" % "3.0.0",
  "org.apache.hadoop" % "hadoop-azure" % "2.7.3"
```
What version of `azure-storage` should I use? I tried randomly 2.2.x 4.x.x 8.x.x
