### ISSUE TITLE
AzureBlobStorage: Exceptions while performing blob operations using azure storage client library(java)

### ISSUE THREAD

**Issue by sankarkumar468** [Azure/azure-storage-java#171]
Hello,
We are using block blobs in azure blob storage.we are using azure-storage-4.0.0.jar. We encountered issues while performing the following operations.
  
  1.Checking existence of the container.
  2.Checking existence of the blob.
  3.Copying one block blob to another block blob.

**1.Checking existence of the container:**
                     The container existence check fails for both cases that if the container does not exist and even if the container exists in azure cloud storage.

           _CloudBlobContainer container=client.getContainerReference(containerName);
           boolean isContainerExists=container.exists();_

When checking existence of the container using **container.exists()** method, the  execution blocks in that method call and no response is received. After 20 minutes,the following exceptions are thrown.

com.microsoft.azure.storage.StorageException: An unknown failure occurred : Connection reset
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:66)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:199)
	at com.microsoft.azure.storage.blob.CloudBlob.exists(CloudBlob.java:1795)
	at com.microsoft.azure.storage.blob.CloudBlob.exists(CloudBlob.java:1782)
	at com.microsoft.azure.storage.blob.CloudBlob.exists(CloudBlob.java:1757)
	at test.Test.CreateContainer(Test.java:383)
	at test.Test.main(Test.java:40)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:119)
	... 5 more

**2.Checking existence of the blob:**
                    While performing blob existence check,the response is received if the blob exists in azure storage and no response is received if the blob does not exist in the azure storage.
              _CloudBlockBlob blob=container.getBlockBlobReference(blobName);
              boolean isBlobExists=blob.exists();_

              While checking existence of the blob using **blob.exists()** method,if the blob exists in azure storage,the response is received immediately.But if the blob does not exist in azure storage the execution blocks in that method call and no response is received.After 20 minutes, the following exceptions are thrown.

com.microsoft.azure.storage.StorageException: An unknown failure occurred : Connection reset
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:66)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:199)
	at com.microsoft.azure.storage.blob.CloudBlob.exists(CloudBlob.java:1795)
	at com.microsoft.azure.storage.blob.CloudBlob.exists(CloudBlob.java:1782)
	at com.microsoft.azure.storage.blob.CloudBlob.exists(CloudBlob.java:1757)
	at test.Test.CreateContainer(Test.java:383)
	at test.Test.main(Test.java:40)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:119)
	... 5 more

**3.Copying one block blob to another block blob:**
             The blob is successfully copied but no response is received and exceptions are thrown.

             _CloudBlockBlob sourceBlob=container.getBlockBlobReference(sourceBlobName);
             CloudBlockBlob targetBlob=container.getBlockBlobReference(targetBlobName);
             targetBlob.startCopy(sourceBlob);_

            while trying to copy one block blob to another block blob using **startCopy()** method,the blob is successfully copied but no response is received.After 2 minutes, the following exceptions are thrown.

The server encountered an unknown failure: Accepted
com.microsoft.azure.storage.StorageException: The server encountered an unknown failure: Accepted
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:101)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:199)
	at com.microsoft.azure.storage.blob.CloudBlob.startCopy(CloudBlob.java:693)
	at com.microsoft.azure.storage.blob.CloudBlockBlob.startCopy(CloudBlockBlob.java:219)
	at com.microsoft.azure.storage.blob.CloudBlockBlob.startCopy(CloudBlockBlob.java:184)
	at BlobStorageApi.CopyBlockBlob(BlobStorageAPI.java:129)
	at BlobStorageApi.main(BlobStorageAPI.java:20)
Caused by: java.lang.NullPointerException
	at com.microsoft.azure.storage.blob.CloudBlob$5.preProcessResponse(CloudBlob.java:736)
	at com.microsoft.azure.storage.blob.CloudBlob$5.preProcessResponse(CloudBlob.java:703)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:139)
	... 5 more

Is there something else that needs to be done while performing these operations?We are hoping to get solution from you.Thanks in advance.

**Comment by jofriedm-msft** [comment]
Hi @sankarkumar468 , have you checked the speed of the machine performing the requests? If that seems fine I would look into using/creating a storage account that is physically closer. You can also try setting a small timeoutInterval and use a large maximumExecutionTime in your blobRequestOptions so that single failures will be retried more quickly. If none of the above works, perhaps use fiddler to verify that you are sending and receiving a response as expected.

**Comment by zhing** [comment]
@sankarkumar468 have you solved this problem?I encounter it just now

**Comment by venkatpathy** [comment]
Im able to connect using a standalone java app. When i do the same with another docker container it gets stuck and after a while i get that exception. not sure if it has something to do with docker compose setup?
CloudBlockBlob blockBlob2 = container.getBlockBlobReference("uploadtest.tmp");
**_blockBlob2.upload(targetStream, targetStream.available());_** -> stops here..
