### ISSUE TITLE
Strange error adding a message in a queue

### ISSUE THREAD

**Issue by diegovisentin** [Azure/azure-storage-java#188]
Hi,
I have a strange problem with adding messages to queues. 
The program freezes on queue.addMessage() and then after few minutes throws the exception reported below. 
Using Storage Explorer, the message results duplicated many times. 
Fiddler confirms that library sends the POST 4 times!
To be sure that it doesn't depend on my code, I tried the QueueBasics sample but the wrong result is the same.

```
The Azure storage client library sample QueueBasics starting...
Got an exception from running samples. Exception details:
com.microsoft.azure.storage.StorageException: The server encountered an unknown failure: Created
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:102)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:200)
	at com.microsoft.azure.storage.queue.CloudQueue.addMessage(CloudQueue.java:269)
	at com.microsoft.azure.storage.queue.CloudQueue.addMessage(CloudQueue.java:214)
	at QueueBasics.main(QueueBasics.java:66)
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(Unknown Source)
	at com.microsoft.azure.storage.queue.QueueMessageHandler.readMessages(QueueMessageHandler.java:71)
	at com.microsoft.azure.storage.queue.CloudQueue$1.preProcessResponse(CloudQueue.java:310)
	at com.microsoft.azure.storage.queue.CloudQueue$1.preProcessResponse(CloudQueue.java:283)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:139)
	... 3 more
```

**Comment by diegovisentin** [comment]
Using the jar downloaded directly from the Maven repository [(link)](https://mvnrepository.com/artifact/com.microsoft.azure/azure-storage), the problem magically disappears.
Comparing my compiled jar with this version, many class files result different (but not all files).
I don't know why but I can suppose the use of JDK 8.
The problem is addressed but I stay perplexed... could someone be so kind to explain me reason of this issue?

Ciao, Diego

**Comment by diegovisentin** [comment]
No answer, so close this issue
