### ISSUE TITLE
Getting error on specific Blob being coppied from a linux machine to a blob container

### ISSUE THREAD

**Issue by dillrye** [Azure/azure-storage-java#190]
I am getting the following Exception:

java.io.IOException
        at com.microsoft.azure.storage.core.Utility.initIOException(Utility.java:770)
        at com.microsoft.azure.storage.blob.BlobOutputStreamInternal.writeBlock(BlobOutputStreamInternal.java:443)
        at com.microsoft.azure.storage.blob.BlobOutputStreamInternal.access$000(BlobOutputStreamInternal.java:52)
        at com.microsoft.azure.storage.blob.BlobOutputStreamInternal$1.call(BlobOutputStreamInternal.java:387)
        at com.microsoft.azure.storage.blob.BlobOutputStreamInternal$1.call(BlobOutputStreamInternal.java:384)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.microsoft.azure.storage.StorageException: The specified blob or block content is invalid.
        at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:89)
        at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:315)
        at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:176)
        at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadBlockInternal(CloudBlockBlob.java:1072)
        at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadBlock(CloudBlockBlob.java:1044)
        at com.microsoft.azure.storage.blob.BlobOutputStreamInternal.writeBlock(BlobOutputStreamInternal.java:437)

I did some searching, and it looks like people general get this message "The specified blob or block content is invalid" when they stop a file copy and then later try to repeat the process.  Is there an easy way I can force this to work?

Note:  This is on only one of my files in a list of about 70 files being coppied. All other files are working, smaller and larger.

**Comment by jofriedm-msft** [comment]
Hi @dillrye, if it is only a single file that has been giving you trouble and it isn't too large, you can try doing downloading the file and then re-uploading it to the desired location

**Comment by dillrye** [comment]
After some more research it looks like the issue is due to a cancelled upload.  Uncommitted blocks existed that did not allow me to re-upload the same file.  I was able to fix the problem by uploading a single byte file of the same name and then deleting it.
