### ISSUE TITLE
NPE in BlobDecryptStream.close

### ISSUE THREAD

**Issue by benoitbr** [Azure/azure-storage-java#198]
The close method can be called before the `cryptoStream` field to be initialized by the `write` method.

I encountered the following error:
```
Caused by: com.microsoft.azure.storage.StorageException: The server encountered an unknown failure: Partial Content
        at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:101)
        at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:199)
        at com.microsoft.azure.storage.blob.CloudBlob.downloadRangeInternal(CloudBlob.java:1492)
        at com.microsoft.azure.storage.blob.CloudBlob.downloadRangeToByteArray(CloudBlob.java:1566)
        ...
Caused by: java.lang.NullPointerException
        at com.microsoft.azure.storage.blob.BlobDecryptStream.close(BlobDecryptStream.java:59)
        at com.microsoft.azure.storage.blob.CloudBlob$9.postProcessResponse(CloudBlob.java:1419)
        at com.microsoft.azure.storage.blob.CloudBlob$9.postProcessResponse(CloudBlob.java:1310)
        at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:146)
        ... 9 more
```

**Comment by jofriedm-msft** [comment]
Hi @benoitbr , what version of the library are you using? Can you share repro code? We can see about adding a null pointer check but it seems like there is another underlying issue if close() is being called before write().

**Comment by benoitbr** [comment]
This issue does not happen on my computer. I only get it on a virtual machine.
Because of the NPE I cannot see the real issue and tell you if it comes from the library or from my code.

I am using the 5.3.1.
The code calls `CloudBlob.downloadRangeToByteArray` on a encrypted blob.

**Comment by jofriedm-msft** [comment]
Please reopen if you are able to provide repro code

**Comment by benoitbr** [comment]
Hi @jofriedm 

I got the same error today and I managed to catch the real exception:

```
java.io.IOException
	at com.microsoft.azure.storage.core.Utility.initIOException(Utility.java:733)
	at com.microsoft.azure.storage.blob.BlobDecryptStream.write(BlobDecryptStream.java:87)
	at com.microsoft.azure.storage.core.Utility.writeToOutputStream(Utility.java:1325)
	at com.microsoft.azure.storage.blob.CloudBlob$9.postProcessResponse(CloudBlob.java:1410)
	at com.microsoft.azure.storage.blob.CloudBlob$9.postProcessResponse(CloudBlob.java:1310)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:146)
	at com.microsoft.azure.storage.blob.CloudBlob.downloadRangeInternal(CloudBlob.java:1499)
	at com.microsoft.azure.storage.blob.CloudBlob.downloadRangeToByteArray(CloudBlob.java:1573)
	at ...
Caused by: com.microsoft.azure.storage.StorageException: Decryption logic threw error. Please check the inner exception for more details.
	at com.microsoft.azure.storage.blob.BlobEncryptionPolicy.decryptBlob(BlobEncryptionPolicy.java:226)
	at com.microsoft.azure.storage.blob.BlobDecryptStream.write(BlobDecryptStream.java:83)
	... 13 more
Caused by: java.security.NoSuchAlgorithmException: RSA
	at com.microsoft.azure.keyvault.extensions.RsaKey.unwrapKeyAsync(RsaKey.java:316)
	at com.microsoft.azure.storage.blob.BlobEncryptionPolicy.decryptBlob(BlobEncryptionPolicy.java:177)
	... 14 more
```

Someone sent me a file encrypted with the Python SDK and I read it with the Java SDK.
