### ISSUE TITLE
Failed to upload Block BLOB using SAS with a group policy identifier

### ISSUE THREAD

**Issue by vmi** [Azure/azure-storage-java#262]
Hi,

I can upload a block BLOB using SAS **without** a group policy identifier.
But I cannot upload a Block BLOB using SAS **with** a group policy identifier.
The SAS with group policy identifier worked correctly on Microsoft Azure Storage Explorer.

Please see my test code: https://github.com/vmi/sas-test

Result of SAS without a group policy identifier
```
uri=Primary = 'https://********.blob.core.windows.net/test'; Secondary = 'https://********-secondary.blob.core.windows.net/test'
sas=sig=********&se=2018-02-13T07%3A12%3A52Z&sv=2017-04-17&sp=racwdl&sr=c
Uploaded: test.txt
Downloaded: test.txt
Now=2018-02-13T06:12:52.981Z
```

Result of SAS with a group policy identifier
```
uri=Primary = 'https://********.blob.core.windows.net/test'; Secondary = 'https://********-secondary.blob.core.windows.net/test'
sas=sig=********&se=2018-02-13T07%3A11%3A33Z&sv=2017-04-17&si=grouppolicy&sp=racwdl&sr=c
Exception in thread "main" com.microsoft.azure.storage.StorageException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
	at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:89)
	at com.microsoft.azure.storage.core.StorageRequest.materializeException(StorageRequest.java:315)
	at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:175)
	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadFullBlob(CloudBlockBlob.java:883)
	at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:713)
	at com.microsoft.azure.storage.blob.CloudBlob.uploadFromByteArray(CloudBlob.java:1726)
	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadText(CloudBlockBlob.java:1176)
	at com.microsoft.azure.storage.blob.CloudBlockBlob.uploadText(CloudBlockBlob.java:1146)
	at test.SasTest.main(SasTest.java:88)
```

**Comment by mirobers** [comment]
There are two things to check here:
1) Was the SAS created with the correct policy identifier? Adding a policy identifier on the an existing SAS won't work.
2) Does the policy exist on the container being accessed and does it specify any parameters that are redundant with the SAS token? For example, the token contains sp= permissions so therefore the stored policy must *not* specify permissions.

If this doesn't help, please provide a service request ID (obtained from the StorageException trace) and we will take a look.

**Comment by vmi** [comment]
Hi,

Thank you for your information.
The condition No. 2 was causing my problem.
It worked by deleting `setPermissions` from SAS policy settings.

I could not find the document of the condition No.2.
Where is it?

**Comment by mirobers** [comment]
I'm glad the issue is resolved. In the [Access Policy](https://docs.microsoft.com/en-us/rest/api/storageservices/constructing-a-service-sas#specifying-the-access-policy) section of the docs, some parameters are listed as required but with this caveat:

> This field must be omitted if it has been specified in an associated stored access policy.
