### ISSUE TITLE
Intermittent UnknownHostExceptions

### ISSUE THREAD

**Issue by maltalex** [Azure/azure-storage-java#283]
We're having some issues with the latest release of the SDK. 

Process that use it, from time to time, get stuck throwing an `java.net.UnknownHostException` every time they try to access the storage:

	18/04/18 06:01:18.209,W,..... com.microsoft.azure.storage.StorageException:
			at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87)
			at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:209)
			at com.microsoft.azure.storage.table.TableOperation.performInsert(TableOperation.java:362)
			at com.microsoft.azure.storage.table.TableOperation.execute(TableOperation.java:682)
			at com.microsoft.azure.storage.table.CloudTable.execute(CloudTable.java:529)
			at com.microsoft.azure.storage.table.CloudTable.execute(CloudTable.java:496)
			....
	Caused by: java.net.UnknownHostException: ourstorageacccount.table.core.windows.net
			at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
			at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
			at java.net.Socket.connect(Socket.java:589)
			at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
			at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
			at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
			at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
			at sun.net.www.http.HttpClient.New(HttpClient.java:339)
			at sun.net.www.http.HttpClient.New(HttpClient.java:357)
			at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
			at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
			at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
			at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
			at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
			at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
			at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:99)
			... 18 more

We've seen this with both Tables and Queues, on different VMs on Azure West Europe. Now, this could be an actual intermittent network failure, only the process seems to become stuck in this state. If you do an nslookup from the command line, the storage account endpoint seems to resolve just fine. But the process keeps throwing `UnknownHostException`s. At that point, the only recourse is to restart the process, which eliminates the problem.

Specs:
We're running OpenJDK 1.8.0_162 and azure-storage-7.0.0
The processes are running in tomcat 8.5
Both the CloudTable and CloudQueue instances use the default retry policy.

**Comment by rickle-msft** [comment]
Hello! 

Can you please send us some code that will repro the issue so we can take a look? Thanks!

**Comment by maltalex** [comment]
I would if I could. It happened a few times and required us to restart the process. At the moment, we don't know how to reproduce it ourselves.

**Comment by maltalex** [comment]
I understand and share your skepticism. The reason I'm raising this issue here is that if it was indeed a DNS issue, I don't see how restarting the Java process would resolve the issue. During the outage, the storage account dns name resolved just fine from the command line.

Am I sure that it's coming from you guys? No. But perhaps we're not the only ones with this issue, or perhaps one of the developers on your side would have an idea why this could happen. Btw, we haven't seen that issue in over a week after seeing it several times in a row on different machines in the span of a few days before that.

From the exception(s) we know that the process kept trying to connect to the correct storage account so it's not our configuration library or anything like that. We don't use a proxy or anything unexpected that could block the process from correctly resolve the domain name - no hosts file, no tricky iptables configuration, nothing. Just several Ubuntu VMs with several different processes that all use Azure storage. 
Clearly, it could very well be that there was some temporary glitch with the network of those VMs in Azure. That's fine, that's what retries are for. But we've seen these for hours, long after the mysterious glitch went away.

Anyway, to answer your questions:
> Are you onboarding with version 7, or are you upgrading from a previous version of the azure-storage-java library?

We're not onboarding with v7, we've been using Azure storage since 1.2.0 (2014). We've even opened a bug for that version - #30 

>  Can you check for any proxy settings in your jvm?

We've never configured a proxy for the jvm. I don't think I've ever configured a proxy for a jvm in my life. But I can double check tomorrow just to make sure.

> Can you provide some client-side logs that we can take a look at?

I've pasted the interesting bit here. But sure, I'll poke around the log once more tomorrow at work.

**Comment by maltalex** [comment]
Okay, so I went through the logs again, and yeah, it's probably not related to Azure storage. I found a few UnknownHostExceptions for other Azure services such as the Service Bus. They're few and far between, but they're there. I'm closing the issue.

**Comment by TurtleBeach** [comment]
I am currently seeing the same issue attempting to access table storage from within an Azure Windows Container Instance, running a simple spring-boot server. Everything works fine locally (in Netbeans, and then running the container locally). The container is a stock Windows nanoserver image, with Java added (local execution is on Win10 Pro). I am using v8 of the Azure Storage Libraries.

Logs are below (lines with CommandLineRunner are generated by my code). The storage account appears to be visible/valid (no exceptions when the CloudTableClient and CloudTable are created). But as soon as I attempt to get a specific row from the table, the exception is thrown (see 29 lines into the log, which is the result of line 397 in my code, at line 20 in the Logs):

```
2019-05-13 00:57:44.632  INFO 3060 --- [           main] a.c.n.sbtest.demo.DemoApplication        : CommandLineRunner: Engine Intialization Ready (status: 0)
2019-05-13 00:57:44.670  INFO 3060 --- [           main] a.c.n.sbtest.demo.DemoApplication        : CommandLineRunner: Deployment table <Deployments> accessible
2019-05-13 00:57:44.687  INFO 3060 --- [           main] a.c.n.sbtest.demo.DemoApplication        : CommandLineRunner: User <e7c6163e-8c06-4146-b0e4-78fec93e6cce> Container accessible
2019-05-13 01:00:17.755  INFO 3060 --- [nio-8080-exec-7] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2019-05-13 01:00:17.755  INFO 3060 --- [nio-8080-exec-7] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2019-05-13 01:00:17.768  INFO 3060 --- [nio-8080-exec-7] o.s.web.servlet.DispatcherServlet        : Completed initialization in 13 ms
com.microsoft.azure.storage.StorageException:
        at com.microsoft.azure.storage.StorageException.translateException(StorageException.java:87)
        at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:209)
        at com.microsoft.azure.storage.table.QueryTableOperation.performRetrieve(QueryTableOperation.java:178)
        at com.microsoft.azure.storage.table.TableOperation.execute(TableOperation.java:694)
        at com.microsoft.azure.storage.table.CloudTable.execute(CloudTable.java:529)
        at com.microsoft.azure.storage.table.CloudTable.execute(CloudTable.java:496)
        at ai.com.neuralstudio.sbtest.demo.DemoApplication.lambda$commandLineRunner$0(DemoApplication.java:562)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:797)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
        at ai.com.neuralstudio.sbtest.demo.DemoApplication.main(DemoApplication.java:397)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.net.UnknownHostException: neuralstudiotest002.table.core.windows.net
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
        at com.microsoft.azure.storage.core.ExecutionEngine.executeWithRetry(ExecutionEngine.java:115)
        ... 19 more
2019-05-13 01:00:29.420 ERROR 3060 --- [           main] a.c.n.sbtest.demo.DemoApplication        : CommandLineRunner: StorageException com.microsoft.azure.storage.StorageException:  (status: -3)
```
Any insights would be appreciated.
Jack

**Comment by rickle-msft** [comment]
Hi, @TurtleBeach. Is this issue consistent in that creating the table always succeeds but the subsequent request for a row fails? And do you have reason to believe that this issue is Storage specific and not related to some underlying networking issue?

**Comment by TurtleBeach** [comment]
@rickle-msft Yes, the issue happens when attempting to retrieve a row. The table already exists (created independently from the code in the container which is attempting to read a row).
Regarding your second question, I am not at all certain what the underlying cause is. But running the same code in a container locally works (a computer in the Cayman Islands accesses the table in East US data center successfully). An Azure Container Instance, ostensibly in the East US data center, running the same image (uploaded to a Azure Container Registry in East US) fails at the point of attempting to retrieve a row from the table.

**Comment by TurtleBeach** [comment]
@rickle-msft Any insights into this? A similarly phrased question filed at aci-issues on github has gotten zero response from MS (or anyone else). I, in retrospect overly naively, assumed that code that runs in a docker container locally would run in a container instance. Clearly something squirrelly is going on in the interaction of storage libraries and containers (in my latest trial, which yielded the same results, I used version 8.3.0 of the storage libraries; maven says 5.5 is the "managed version" - which also did not work, and my first trials were using 8.0.0). This code, which executes immediately before the attempt to retrieve a row from the table, does not throw exceptions in the container:

`CloudStorageAccount systemAccount = CloudStorageAccount.parse(systemConnection.toString());
CloudTableClient tableClient = systemAccount.createCloudTableClient();
					
current = 2;
CloudTable deploymentTable = tableClient.getTableReference(DEPLOYMENT_TABLE_NAME) ;
					
if (debugging)
  LOG.info(String.format("CommandLineRunner: Deployment table <%s> accessible", DEPLOYMENT_TABLE_NAME));
					
current = 3;
CloudStorageAccount userAccount = CloudStorageAccount.parse(userConnection.toString());
					
CloudBlobClient blobClient = userAccount.createCloudBlobClient();
current = 4;
CloudBlobContainer container = blobClient.getContainerReference( userGUID );
					
if (debugging)
  LOG.info(String.format("CommandLineRunner: User <%s> Container accessible", userGUID));
					
errorOperation = operation = LOADING_DEPLOYMENT;
					
current = 5;
DynamicTableEntity deployRow = (DynamicTableEntity)(deploymentTable.execute((TableOperation.retrieve(userGUID, deployment, DynamicTableEntity.class))).getResultAsType());
`
Jack

**Comment by rickle-msft** [comment]
Can you give us a link to the issue you found on the aci-issues repo? With that, we will try to work with that team to diagnose the problem.

**Comment by TurtleBeach** [comment]
Upon re-reading my sentence above, I realize I was not clear. I meant that I filed a similarly worded (to the issue here) issue at acr-issues and no one seems to be monitoring that feedback site (i.e., silence from MS).
That said, here is the link: https://github.com/microsoftfeedback/aci-issues/issues

**Comment by TurtleBeach** [comment]
Also, here is the relevant portion of POM:

    <parent>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-parent</artifactId>
      <version>2.1.4.RELEASE</version>
      <relativePath/> 
    </parent>

    <groupId>ai.com.neuralstudio.sbtest</groupId>
    <artifactId>demo</artifactId>
    <version>0.0.2-SNAPSHOT</version>
    <name>demo</name>
    <description>Demo project for Spring Boot</description>

    <properties>
      <java.version>1.8</java.version>
      <azure.version>2.1.2</azure.version>
    </properties>

    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-actuator</artifactId>
      </dependency>

      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-web</artifactId>
      </dependency>

      <dependency>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>azure-spring-boot-starter</artifactId>
        <version>2.1.6</version>
      </dependency>

      <dependency>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>azure-storage-spring-boot-starter</artifactId>
      </dependency>

      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-devtools</artifactId>
        <scope>runtime</scope>
      </dependency>

      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-test</artifactId>
        <scope>test</scope>
      </dependency>

      
      <dependency>
        <groupId>com.microsoft.azure</groupId>
        <artifactId>azure-storage</artifactId>
        <version>8.3.0</version>
        <type>jar</type>
      </dependency>

Let me know if anything else would be useful.

**Comment by TurtleBeach** [comment]
@rickle-msft FYI, it appears that the issue is the result of problems in most, if not all, of the most current Microsoft server images (with and without Powershell). Based on investigations by jakaruna-MSFT in MSDN forum, I tried the windows servercore 1607 for AMD64 (specifically:
`  mcr.microsoft.com/windows/servercore:1607-KB4505052-amd64`
and that image worked (with all other software added, just as with the images that failed).
On a whim, I tried recent servercore images (1809) with and without Powershell, and I tried an image that supposedly is for long term support
`   mcr.microsoft.com/windows/servercore:ltsc2019`
and they all failed. It is disappointing, to say the least, that a serious bug or omission was introduced after the 1607 image was released. I have wasted a good portion of 3 calendar weeks on this issue, and would still be dead in the water were it not for jakaruna-MSFT investigating. And I suspect he would rather be doing, and probably ought to be doing, things other than finding problems with released software.

**Comment by maltalex** [comment]
@TurtleBeach It's not mentioned it in the original issue, but all of our servers are (and were) Linux-based.

I haven't followed the issue closely since you reopened it, but now that you mention Windows as the culprit, I though you should know.

**Comment by TurtleBeach** [comment]
@maltalex Thanks.  Presumably the issue will be addressed by MS, though currently the silence is deafening.

**Comment by rickle-msft** [comment]
@TurtleBeach. Thank you for posting that information. As my lack of follow up may have indicated, I had difficulty getting relevant teams to look into the request. I am glad you had better luck on the MSDN forum and I apologize that I was not able to catalyze the response more effectively.

If you feel that the response by jakaruna-MSFT was sufficient and that the issue has been appropriately acknowledge with a pending fix, then I think we are in as good a spot as we can be. If you are concerned that the bug was not adequately filed, I will be happy to make another effort at reaching out to the team and encourage them to release a fix.

**Comment by srisathiya01** [comment]
Even afer configured proxy we are facing the unkownhostexception

BlobContainerClient blobContainerClient = new BlobContainerClientBuilder()
				    .endpoint("<url+sastoken>")
				    .httpClient(client)
				    .buildClient();
		

InetSocketAddress proxyService = new InetSocketAddress("<proxyip>",<port>);
		 
ProxyOptions proxyOptions = new ProxyOptions(ProxyOptions.Type.HTTP, proxyService)
		     .setCredentials("<username>", "<Password>");
		 
		 HttpClient client = new NettyAsyncHttpClientBuilder()
				    .proxy(proxyOptions)
				    .build();
		
reactor.core.Exceptions$ReactiveException: java.net.UnknownHostException: XXXXX.blob.core.windows.net
	at reactor.core.Exceptions.propagate(Exceptions.java:393)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)
	at reactor.core.publisher.Mono.block(Mono.java:1679)
	at com.azure.storage.common.implementation.StorageImplUtils.blockWithOptionalTimeout(StorageImplUtils.java:99)
	at com.azure.storage.blob.specialized.BlockBlobClient.uploadWithResponse(BlockBlobClient.java:316)
	at com.azure.storage.blob.specialized.BlockBlobClient.uploadWithResponse(BlockBlobClient.java:283)
	at com.azure.storage.blob.specialized.BlockBlobClient.upload(BlockBlobClient.java:241)
	at com.renault.puc.common.example.TestGcs.testAzureUpload(TestGcs.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		... 56 more
Caused by: java.net.UnknownHostException: XXXXXX.blob.core.windows.net
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at java.net.InetAddress.getByName(InetAddress.java:1076)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
	at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
	at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:984)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:504)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:417)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:474)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
