### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError caused by dependency conflict issue for com.fasterxml.jackson.core:jackson-core:jar 

### ISSUE THREAD

**Issue by LeoAugust19** [Azure/azure-storage-java#345]
### Which service(blob, file, queue, table) does this issue concern?
com.microsoft.azure:azure-storage-samples-logging:jar:0.0.1-SNAPSHOT pom. xml

### Which version of the SDK was used?
JDK 1.7

### What problem was encountered?

Hi, in **com.microsoft.azure:azure-storage-samples-logging:jar:0.0.1-SNAPSHOT**, as show in the following dependency tree, there are multiple version of **com.fasterxml.jackson.core:jackson-core:jar**.
Based on Maven's "nearest wins strategy", only the older version 2.6.0 that nearer to the root (host project) will be loaded. 

However, the method **<com.fasterxml.jackson.core.JsonParseException: void <init>(com.fasterxml.jackson.core.JsonParser,java.lang.String,com.fasterxml.jackson.core.JsonLocation)>** only defined in jackson-core. 2.7.2 and not included in 2.6.0. when referencing this method, we crashes with the **java.lang.NoSuchMethodError** exception.

#### stack trace:

Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonParseException.<init>(Lcom/fasterxml/jackson/core/JsonParser;Ljava/lang/String;Lcom/fasterxml/jackson/core/JsonLocation;)V
	at com.fasterxml.jackson.databind.node.TextNode._reportInvalidBase64(TextNode.java:295)
	at com.fasterxml.jackson.databind.node.TextNode._reportInvalidBase64(TextNode.java:271)
	at com.fasterxml.jackson.databind.node.TextNode.getBinaryValue(TextNode.java:80)
	at com.fasterxml.jackson.databind.node.TextNode.binaryValue(TextNode.java:156)
	at com.fasterxml.jackson.databind.node.TreeTraversingParser.getBinaryValue(TreeTraversingParser.java:350)
	at com.fasterxml.jackson.core.JsonParser.getBinaryValue(JsonParser.java:1220)
	at com.microsoft.azure.storage.core.EncryptionData.deserialize(EncryptionData.java:216)

### dependency tree:

com.microsoft.azure:azure-storage-samples-logging:jar:0.0.1-SNAPSHOT
+- com.microsoft.azure:azure-storage:jar:7.0.0:compile
|  +- **com.fasterxml.jackson.core:jackson-core:jar:2.6.0:compile**
|  +- (org.slf4j:slf4j-api:jar:1.7.12:compile - omitted for duplicate)
|  +- org.apache.commons:commons-lang3:jar:3.4:compile
|  \- com.microsoft.azure:azure-keyvault-core:jar:1.0.0:compile
|     +- (org.apache.commons:commons-lang3:jar:3.4:compile - omitted for duplicate)
|     \- (com.google.guava:guava:jar:20.0:compile - omitted for duplicate)
+- com.microsoft.azure:azure-keyvault-extensions:jar:1.0.0:compile
|  +- com.microsoft.azure:azure-client-runtime:jar:1.0.0:compile
|  |  \- com.microsoft.rest:client-runtime:jar:1.0.0:compile
|  |     +- (com.google.guava:guava:jar:20.0:compile - omitted for duplicate)
|  |     +- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.7.2:compile
|  |     |  +- (com.fasterxml.jackson.core:jackson-annotations:jar:2.7.0:compile - omitted for duplicate)
|  |     |  +- **(com.fasterxml.jackson.core:jackson-core:jar:2.7.2:compile - omitted for conflict with 2.6.0)**
|  |     |  +- (com.fasterxml.jackson.core:jackson-databind:jar:2.7.2:compile - omitted for duplicate)
|  |     |  \- joda-time:joda-time:jar:2.4:compile
|  |     +- (org.apache.commons:commons-lang3:jar:3.4:compile - omitted for duplicate)
|  |     \- (org.slf4j:slf4j-api:jar:1.7.22:compile - omitted for conflict with 1.7.12)
|  +- com.microsoft.azure:azure-keyvault-webkey:jar:1.0.0:compile
|  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.7.2:compile
|  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.7.0:compile
|  |  |  \- **(com.fasterxml.jackson.core:jackson-core:jar:2.7.2:compile - omitted for conflict with 2.6.0)**
|  |  +- (commons-codec:commons-codec:jar:1.10:compile - omitted for duplicate)
|  |  \- (com.google.guava:guava:jar:20.0:compile - omitted for duplicate)

### Have you found a mitigation/solution?

Could you please upgrade com.fasterxml.jackson.core:jackson-core:jar:2.6.0:compile to 2.7.2 version in com.microsoft.azure:azure-storage?

Hope this report can help you!

Best regards,
Leo

**Comment by rickle-msft** [comment]
Hi, @LeoAugust19.

Thank you so much for bringing this to our attention. This was definitely an oversight in updating our dependencies during our last release. I have added this to our backlog, and we will update this as soon as we can.

**Comment by LeoAugust19** [comment]
Hi, @rickle-msft , thanks a lot! The reported dependency issue is detected by an automated test case generation tool.

As some complex branches are difficult to cover, to trigger the execution of missing method, we mutated one of your source file before testing. We forced the conditional statement of branch:

 **else if (name.equals(Constants.EncryptionConstants.CONTENT_ENCRYPTION_IV))**  in method **EncryptionData deserialize(JsonParser parser)** to be "TRUE". After executing this branch, we then got the above stack trace.

![192401](https://user-images.githubusercontent.com/41102283/43457706-44685110-94fa-11e8-99c7-b85136833333.png)

Could please check whether the mutated branch condition is reasonable?

Removing the dependency conflict problem will benefit the software maintenance. ^_^

Thanks again!
Leo

Test case executed with the mutated program:
[Test2.txt](https://github.com/Azure/azure-storage-java/files/2245161/Test2.txt)

Mutated program:
[EncryptionData_mutated.txt](https://github.com/Azure/azure-storage-java/files/2245157/EncryptionData_mutated.txt)

Original program:
[EncryptionData_original.txt](https://github.com/Azure/azure-storage-java/files/2245158/EncryptionData_original.txt)

**Comment by rickle-msft** [comment]
Hi, @LeoAugust19.

Sorry I missed your comment the other day. We just updated master to fix the pom for the logging sample, so you can give that a go. It didn't depend on Jackson directly, but it depended on v7 of the library. We updated it to depend on v8 of the library, which pulled in the new Jackson dependency. It should be working now, and I think that should relieve you of having to modify the branch condition as you have above. 
If you are satisfied with the fix and have no further questions, could you please close the issue? Otherwise, please feel free to raise any follow up questions you have.

**Comment by LeoAugust19** [comment]
https://github.com/Azure/azure-storage-java/commit/5a3b1966d21d02899796fcab0e77c9a8278777c5

**Comment by LeoAugust19** [comment]
@rickle-msft Thanks for your feedback.

**Comment by LeoAugust19** [comment]
@rickle-msft Thank you very much. I have a further quetion: Is the modified branch condition reasonable? Will the modified branch (forced to be TRUE) be executed actually?
Thanks again.

BR,
Leo

**Comment by mirobers** [comment]
@LeoAugust19 You are asking if this is a false positive I believe. Although the way you arrived at the parse error is artificial, I believe that a similar parse error at that point in the code is achievable in actual usage, presumably leading to the missing method due to dependency conflict (if indeed such a conflict exists in the application code).

Do note that this isn't a bug in the library (because the dependency conflict must come from the application) and it isn't precisely a bug in the sample (because the sample never hits the parse error). Despite that, this did bring to our attention that the sample needed to update to the latest library version so I would not call it a false positive.

Would you mind sharing some information about the test case generation tool you are using?

**Comment by LeoAugust19** [comment]
@mirobers Thanks for your comments.
The automated test case generation tool is under development, which aims to trigger the crashes caused by dependency conflicts and help developers identify the missing features. One limitation is that it may generate false positive results, as we artificially mutate the branch conditions to force their execution. 

Of course, we all have the same objectives to ensure the projects’ long-term health and improve their maintainability.

Thanks again!
BR,
Leo

**Comment by mirobers** [comment]
@LeoAugust19 If I had to choose I'd say that the stack trace is more useful because this is how we can decide the feasibility of reproducing the issue.

By the way, shall I wish you a happy birthday? I am not sure what the August19 in your name refers to. :)

**Comment by skillwind** [comment]
@mirobers Thank you very very very very very very .... much.  ;-p

**Comment by LeoAugust19** [comment]
@mirobers Thank you very very very very very very very very .... much. ;-p
