### ISSUE TITLE
TransferManager fails on uploading large files (> 2 GB)

### ISSUE THREAD

**Issue by rsteph-de** [Azure/azure-storage-java#374]
https://github.com/Azure/azure-storage-java/blob/ebdc21465a57ed5cb6fdd119848884dc1bb87d34/src/main/java/com/microsoft/azure/storage/blob/TransferManager.java#L104

The maximum Integer value  2147483647.
When processing files larger than 2 GB the casting of (file.size() ...) from long to int may lead to negative values, because the value range for integer does not fit.
This results in a negative count value.

Suggested solution: 
use Math.min(long, long) and cast the result to int:
`int count = (int)Math.min(blockLength, (file.size() - i * blockLength));`

**Comment by rickle-msft** [comment]
Hi, @rsteph-de. Thank you for reporting this. Your logic certainly makes sense, and it uncovered a bug in our tests as well that was preventing us from catching this, so thank you again. I've added this to our backlog and hopefully we can get this in for the next release.

**Comment by rsteph-de** [comment]
I used
```
            TransferManager.uploadFileToBlockBlob(fileChannel, blobURL, 8 * 1024 * 1024, options)
                .subscribe(response -> {
                    System.out.println("Completed upload request.");
                    System.out.println(response.response().statusCode());
                });
```
and got the following exception:
```
io.reactivex.exceptions.OnErrorNotImplementedException: Flowable<ByteBuffer> emitted more bytes than the expected -1169738490
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:47)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onError(SingleFlatMap.java:90)
	at io.reactivex.internal.operators.observable.ObservableCollectSingle$CollectObserver.onError(ObservableCollectSingle.java:112)
	at io.reactivex.internal.operators.observable.ObservableConcatMapEager$ConcatMapEagerMainObserver.drain(ObservableConcatMapEager.java:301)
	at io.reactivex.internal.operators.observable.ObservableConcatMapEager$ConcatMapEagerMainObserver.innerError(ObservableConcatMapEager.java:209)
	at io.reactivex.internal.observers.InnerQueuedObserver.onError(InnerQueuedObserver.java:89)
	at io.reactivex.internal.observers.DeferredScalarDisposable.error(DeferredScalarDisposable.java:100)
	at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onError(SingleToObservable.java:77)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
	at io.reactivex.internal.observers.ResumeSingleObserver.onError(ResumeSingleObserver.java:51)
	at io.reactivex.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:78)
	at io.reactivex.internal.operators.single.SingleError.subscribeActual(SingleError.java:42)
	at io.reactivex.Single.subscribe(Single.java:3394)
	at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onError(SingleResumeNext.java:80)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onError(SingleFlatMap.java:90)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onError(SingleFlatMap.java:90)
	at io.reactivex.internal.observers.ResumeSingleObserver.onError(ResumeSingleObserver.java:51)
	at io.reactivex.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:78)
	at io.reactivex.internal.operators.single.SingleError.subscribeActual(SingleError.java:42)
	at io.reactivex.Single.subscribe(Single.java:3394)
	at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onError(SingleResumeNext.java:80)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onError(SingleFlatMap.java:90)
	at io.reactivex.internal.observers.ResumeSingleObserver.onError(ResumeSingleObserver.java:51)
	at io.reactivex.internal.operators.single.SingleTimeout$TimeoutMainObserver.onError(SingleTimeout.java:142)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onError(SingleDoOnSuccess.java:64)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onError(SingleFlatMap.java:90)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onError(SingleDoOnSuccess.java:64)
	at io.reactivex.internal.operators.single.SingleDoOnError$DoOnError.onError(SingleDoOnError.java:63)
	at io.reactivex.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:95)
	at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:81)
	at com.microsoft.rest.v2.http.NettyClient$AcquisitionListener.emitError(NettyClient.java:432)
	at com.microsoft.rest.v2.http.NettyClient$AcquisitionListener$RequestSubscriber.onError(NettyClient.java:353)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onError(FlowableDoOnEach.java:111)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onError(FlowableDoOnEach.java:111)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.fail(BasicFuseableSubscriber.java:111)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:88)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmitScalar(FlowableFlatMap.java:234)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:152)
	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:69)
	at com.microsoft.rest.v2.util.FlowableUtil$FileReadFlowable$FileReadSubscription.drain(FlowableUtil.java:311)
	at com.microsoft.rest.v2.util.FlowableUtil$FileReadFlowable$FileReadSubscription.completed(FlowableUtil.java:383)
	at com.microsoft.rest.v2.util.FlowableUtil$FileReadFlowable$FileReadSubscription.completed(FlowableUtil.java:258)
	at sun.nio.ch.Invoker.invokeUnchecked(Unknown Source)
	at sun.nio.ch.Invoker$2.run(Unknown Source)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.microsoft.rest.v2.http.UnexpectedLengthException: Flowable<ByteBuffer> emitted more bytes than the expected -1169738490
	at com.microsoft.rest.v2.util.FlowableUtil$1.lambda$call$0(FlowableUtil.java:88)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:86)
	... 12 more
Exception in thread "Thread-5" io.reactivex.exceptions.OnErrorNotImplementedException: Flowable<ByteBuffer> emitted more bytes than the expected -1169738490
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
	at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:47)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onError(SingleFlatMap.java:90)
	at io.reactivex.internal.operators.observable.ObservableCollectSingle$CollectObserver.onError(ObservableCollectSingle.java:112)
	at io.reactivex.internal.operators.observable.ObservableConcatMapEager$ConcatMapEagerMainObserver.drain(ObservableConcatMapEager.java:301)
	at io.reactivex.internal.operators.observable.ObservableConcatMapEager$ConcatMapEagerMainObserver.innerError(ObservableConcatMapEager.java:209)
	at io.reactivex.internal.observers.InnerQueuedObserver.onError(InnerQueuedObserver.java:89)
	at io.reactivex.internal.observers.DeferredScalarDisposable.error(DeferredScalarDisposable.java:100)
	at io.reactivex.internal.operators.single.SingleToObservable$SingleToObservableObserver.onError(SingleToObservable.java:77)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
	at io.reactivex.internal.observers.ResumeSingleObserver.onError(ResumeSingleObserver.java:51)
	at io.reactivex.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:78)
	at io.reactivex.internal.operators.single.SingleError.subscribeActual(SingleError.java:42)
	at io.reactivex.Single.subscribe(Single.java:3394)
	at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onError(SingleResumeNext.java:80)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onError(SingleFlatMap.java:90)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onError(SingleFlatMap.java:90)
	at io.reactivex.internal.observers.ResumeSingleObserver.onError(ResumeSingleObserver.java:51)
	at io.reactivex.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:78)
	at io.reactivex.internal.operators.single.SingleError.subscribeActual(SingleError.java:42)
	at io.reactivex.Single.subscribe(Single.java:3394)
	at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onError(SingleResumeNext.java:80)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onError(SingleFlatMap.java:90)
	at io.reactivex.internal.observers.ResumeSingleObserver.onError(ResumeSingleObserver.java:51)
	at io.reactivex.internal.operators.single.SingleTimeout$TimeoutMainObserver.onError(SingleTimeout.java:142)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onError(SingleDoOnSuccess.java:64)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onError(SingleFlatMap.java:90)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onError(SingleDoOnSuccess.java:64)
	at io.reactivex.internal.operators.single.SingleDoOnError$DoOnError.onError(SingleDoOnError.java:63)
	at io.reactivex.internal.operators.single.SingleCreate$Emitter.tryOnError(SingleCreate.java:95)
	at io.reactivex.internal.operators.single.SingleCreate$Emitter.onError(SingleCreate.java:81)
	at com.microsoft.rest.v2.http.NettyClient$AcquisitionListener.emitError(NettyClient.java:432)
	at com.microsoft.rest.v2.http.NettyClient$AcquisitionListener$RequestSubscriber.onError(NettyClient.java:353)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onError(FlowableDoOnEach.java:111)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onError(FlowableDoOnEach.java:111)
	at io.reactivex.internal.subscribers.BasicFuseableSubscriber.fail(BasicFuseableSubscriber.java:111)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:88)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.tryEmitScalar(FlowableFlatMap.java:234)
	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:152)
	at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(FlowableMap.java:69)
	at com.microsoft.rest.v2.util.FlowableUtil$FileReadFlowable$FileReadSubscription.drain(FlowableUtil.java:311)
	at com.microsoft.rest.v2.util.FlowableUtil$FileReadFlowable$FileReadSubscription.completed(FlowableUtil.java:383)
	at com.microsoft.rest.v2.util.FlowableUtil$FileReadFlowable$FileReadSubscription.completed(FlowableUtil.java:258)
	at sun.nio.ch.Invoker.invokeUnchecked(Unknown Source)
	at sun.nio.ch.Invoker$2.run(Unknown Source)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.microsoft.rest.v2.http.UnexpectedLengthException: Flowable<ByteBuffer> emitted more bytes than the expected -1169738490
	at com.microsoft.rest.v2.util.FlowableUtil$1.lambda$call$0(FlowableUtil.java:88)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:86)
	... 12 more
```
Using a debugger I found the faulty line.

**Comment by rickle-msft** [comment]
Excellent. Thank you for that. I will keep you posted on progress here
