### ISSUE TITLE
Azure blob与Azure table不兼容，无法创建在同一个项目中

### ISSUE THREAD

**Issue by sunliangtian** [Azure/azure-storage-java#420]
### Which service(blob, file, queue, table) does this issue concern?
blob，table

### Which version of the SDK was used?

        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-storage</artifactId>
            <version>8.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-storage-blob</artifactId>
            <version>10.3.0</version>
        </dependency>

### What problem was encountered?
Exception in thread "main" java.lang.NoSuchFieldError: NONE
	at com.microsoft.azure.storage.blob.ListBlobsOptions.<init>(ListBlobsOptions.java:36)
	at com.microsoft.azure.storage.blob.ListBlobsOptions.<clinit>(ListBlobsOptions.java:27)
	at quickstart.Quickstart.listBlobs(Quickstart.java:67)
	at quickstart.Quickstart.main(Quickstart.java:188)

### Have you found a mitigation/solution?
包路径重命名

**Comment by zezha-msft** [comment]
Hi @sunliangtian, thanks for reaching out!

This is a known issue already being tracked at #400.
