### ISSUE TITLE
NPE when referencing a blob store that doesn't exist

### ISSUE THREAD

**Issue by bobvanmanen** [Azure/azure-storage-java#440]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
10.4.0

### What problem was encountered?
A NullPointerException is thrown when connecting to a blob store that doesn't exist:

```
2019-02-25 07:53:48.003 WARN : An exception was thrown by com.microsoft.rest.v2.http.NettyClient$AcquisitionListener.operationComplete()
java.lang.NullPointerException: null
	at com.microsoft.rest.v2.http.NettyClient$AcquisitionListener.emitError(NettyClient.java:425)
	at com.microsoft.rest.v2.http.NettyClient$AcquisitionListener.operationComplete(NettyClient.java:246)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:511)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:485)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:33
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:435)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:474)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

It happens at this statement in `NettyClient$AcquisitionListener.emitError`:

```
LOGGER.warn("Error emitted on channel {}. Message: {}", channel.id(), throwable.getMessage());
```

The reason is that `channel` is not assigned when `emitError` is called. You can see this in `NettyClient$AcquisitionListener.operationComplete`: 

```           
if (!cf.isSuccess()) {
     emitError(cf.cause());
     return;
}
channel = (Channel) cf.getNow();
```

### Have you found a mitigation/solution?

none aside from referencing a blob store that does exist.

**Comment by rickle-msft** [comment]
Hi, @bobvanmanen. We apologize for the inconvenience this issues causes. This issue is being tracked on the [repo that contains the NettyClient](https://github.com/Azure/autorest-clientruntime-for-java/issues/538). Please follow up there for further discussion. We will reach out to that team again to encourage active resolution.

**Comment by bobvanmanen** [comment]
Thanks for the quick follow up and referencing the correct repository! I only ran into it when one of our blob stores was unexpectedly removed (by an automated process).

**Comment by rickle-msft** [comment]
Gotcha. I'm glad to hear it doesn't sound like it's a major blocker for you, but still good for us to fix.

**Comment by jacobw125** [comment]
@rickle-msft, we're seeing the same exact problem in v11.0.0, when trying to list a container in a storage account that doesn't exist.

We are trying to use this library inside the Play framework which also relies on Netty. When this bug occurs it seems to disrupt Netty, which brings down our app.

Similarly, when I isolate the problem in a standalone Gradle project, my unittest listing a nonexistent storage account hangs indefinitely - the Netty thread seems to die and leaves my test thread deadlocked. 

This is a major blocker for us - our application is business critical and we can't risk bringing it down if a user enters an invalid storage URL. Any suggestions of workarounds would be much appreciated.

**Comment by bobvanmanen** [comment]
@jacobw125 It would be good to also add your comment to the related Netty bug: https://github.com/Azure/autorest-clientruntime-for-java/issues/538. Hopefully, that will cause it to increase priority so we can get a fix.

**Comment by rickle-msft** [comment]
@jacobw125. Thank you for contributing to the conversation. Because the only report of this at the time was not blocking any customers, we did not prioritize it for v11 in favor of other work that addressed some other issues which were at the time blocking customers, so I am not surprised that v11.0.0 did not resolve this. Because you are hitting a business critical scenario, I will look more into this issue and try to promote it in importance to unblock you. I'll follow up here when I have more information.

**Comment by jacobw125** [comment]
Thank you very much @rickle-msft  - there's another workaround I didn't think of before, which is for us to maintain a cached list of known storage accounts, and validate our own URLs before sending an API request. So we do have a path forward in the short term, but that's not ideal - appreciate you following up on this!

**Comment by jianghaolu** [comment]
This is fixed in https://github.com/Azure/autorest-clientruntime-for-java/pull/606.

This in general increases robustness of the `emitError()` method. When a storage account isn't available, this will throw `UnknownHostException`, which will be retried (to allow handling transient network failures) and then thrown eventually.

**Comment by rickle-msft** [comment]
We have released 11.0.1 which depends on the new version of the runtime containing this fix.

**Comment by shubh3695** [comment]
For future readers, After bumping to 11.0.1 the next issue is here https://github.com/Azure/azure-sdk-for-java/issues/4097

**Comment by niku2907** [comment]
@rickle-msft I am observing this issue with 11.0.1 as well. The symptoms are similar:
1. Thread pool getting exhausted.
2. A lot of threads with stack trace as:

```
"nioEventLoopGroup-5-4" #97 daemon prio=5 os_prio=0 cpu=3.34ms elapsed=1065.86s tid=0x0000fffeb81aa000 nid=0xd2 runnable  [0x0000fffec0bfc000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPoll.wait(java.base@11.0.20/Native Method)
	at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@11.0.20/EPollSelectorImpl.java:120)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.20/SelectorImpl.java:124)
	- locked <0x00000000aef4bcb0> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000000aef4bc58> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(java.base@11.0.20/SelectorImpl.java:141)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:68)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:879)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:526)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@11.0.20/Thread.java:829)
```

**Comment by ngupta0205** [comment]
@rickle-msft I am observing this issue with 11.0.1 as well when storage account doesn't exist. The symptoms are similar:
1. Thread pool getting exhausted.
2. A lot of threads with stack trace as:

```
"nioEventLoopGroup-5-4" #97 daemon prio=5 os_prio=0 cpu=3.34ms elapsed=1065.86s tid=0x0000fffeb81aa000 nid=0xd2 runnable  [0x0000fffec0bfc000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPoll.wait(java.base@11.0.20/Native Method)
	at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@11.0.20/EPollSelectorImpl.java:120)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.20/SelectorImpl.java:124)
	- locked <0x00000000aef4bcb0> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000000aef4bc58> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(java.base@11.0.20/SelectorImpl.java:141)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:68)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:879)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:526)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(java.base@11.0.20/Thread.java:829)
```
