### ISSUE TITLE
BlockBlobURL.download() not capable of closing connection

### ISSUE THREAD

**Issue by pavelkryl** [Azure/azure-storage-java#446]
### Which service(blob, file, queue, table) does this issue concern?
BlockBlobURL

### Which version of the SDK was used?
10.3.0

### What problem was encountered?
60 seconds after downloading the BLOB (successfully), I have encountered following in the console:

`2019-03-04T07:51:34.763Z WARN c.m.a.s.p.RequestResponseLink /ReactorThread9d3053c2-48a4-43ca-96ec-234b7e720e62/ [traceId:,parentId:,spanId:] - Internal send link 'RequestResponseLink-Sender_0467f8_70ef1045a38a49d9a9b0b6c53ce2354b_G0' of requestresponselink to '$cbs' encountered error. com.microsoft.azure.servicebus.amqp.AmqpException: The connection was inactive for more than the allowed 60000 milliseconds and is closed by container 'LinkTracker'. TrackingId:70ef1045a38a49d9a9b0b6c53ce2354b_G0, SystemTracker:gateway7, Timestamp:2019-03-04T07:51:33߬	... 10 more߬Wrapped by: com.microsoft.azure.servicebus.primitives.ServiceBusException: com.microsoft.azure.servicebus.amqp.AmqpException: The connection was inactive for more than the allowed 60000 milliseconds and is closed by container 'LinkTracker'. TrackingId:70ef1045a38a49d9a9b0b6c53ce2354b_G0, SystemTracker:gateway7, Timestamp:2019-03-04T07:51:33߬	at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:90) ~[azure-servicebus-1.2.11.jar:?]߬	at com.microsoft.azure.servicebus.primitives.RequestResponseLink$InternalSender.onClose(RequestResponseLink.java:862) [azure-servicebus-1.2.11.jar:?]߬	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:68) [azure-servicebus-1.2.11.jar:?]߬	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:42) [azure-servicebus-1.2.11.jar:?]߬	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176) [proton-j-0.31.0.jar:?]߬	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) [proton-j-0.31.0.jar:?]߬	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) [proton-j-0.31.0.jar:?]߬	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) [proton-j-0.31.0.jar:?]߬	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:483) [azure-servicebus-1.2.11.jar:?]߬	at java.lang.Thread.run(Thread.java:834) [?:?]߬
2019-03-04T07:51:34.765Z WARN c.m.a.s.p.RequestResponseLink /ReactorThread9d3053c2-48a4-43ca-96ec-234b7e720e62/ [traceId:,parentId:,spanId:] - Internal receive link 'RequestResponseLink-Receiver_91b258_70ef1045a38a49d9a9b0b6c53ce2354b_G0' of requestresponselink to '$cbs' encountered error. com.microsoft.azure.servicebus.amqp.AmqpException: The connection was inactive for more than the allowed 60000 milliseconds and is closed by container 'LinkTracker'. TrackingId:70ef1045a38a49d9a9b0b6c53ce2354b_G0, SystemTracker:gateway7, Timestamp:2019-03-04T07:51:33߬	... 10 more߬Wrapped by: com.microsoft.azure.servicebus.primitives.ServiceBusException: com.microsoft.azure.servicebus.amqp.AmqpException: The connection was inactive for more than the allowed 60000 milliseconds and is closed by container 'LinkTracker'. TrackingId:70ef1045a38a49d9a9b0b6c53ce2354b_G0, SystemTracker:gateway7, Timestamp:2019-03-04T07:51:33߬	at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:90) ~[azure-servicebus-1.2.11.jar:?]߬	at com.microsoft.azure.servicebus.primitives.RequestResponseLink$InternalReceiver.onClose(RequestResponseLink.java:679) [azure-servicebus-1.2.11.jar:?]߬	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:68) [azure-servicebus-1.2.11.jar:?]߬	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:42) [azure-servicebus-1.2.11.jar:?]߬	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176) [proton-j-0.31.0.jar:?]߬	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) [proton-j-0.31.0.jar:?]߬	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) [proton-j-0.31.0.jar:?]߬	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) [proton-j-0.31.0.jar:?]߬	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:483) [azure-servicebus-1.2.11.jar:?]߬	at java.lang.Thread.run(Thread.java:834) [?:?]߬
2019-03-04T07:51:34.767Z ERROR c.m.a.s.p.MessagingFactory /ReactorThread9d3053c2-48a4-43ca-96ec-234b7e720e62/ [traceId:,parentId:,spanId:] - Connection error. 'Error{condition=amqp:connection:forced, description='The connection was inactive for more than the allowed 60000 milliseconds and is closed by container 'LinkTracker'. TrackingId:70ef1045a38a49d9a9b0b6c53ce2354b_G0, SystemTracker:gateway7, Timestamp:2019-03-04T07:51:33', info=null}' 
2019-03-04T07:51:34.767Z INFO c.m.a.s.p.MessagingFactory /ReactorThread9d3053c2-48a4-43ca-96ec-234b7e720e62/ [traceId:,parentId:,spanId:] - Closing connection to host `

### Have you found a mitigation/solution?

No.

I would like to be able to close the connection by myself, but the API does not allow me to do so. Anyway I think that the implementation should close the connection right after the content is downloaded, in it's onComplete. Or it should keep it alive for potential further operations and close it after a given timeout (without those WARNings/ERRORs log messages).

**Comment by pavelkryl** [comment]
I am sorry, the error message was caused by some other activity/connection. Closing issue.
