### ISSUE TITLE
blob.upload is taking long time to upload Big file 

### ISSUE THREAD

**Issue by chhajerpawan** [Azure/azure-storage-java#452]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?

8.0.0

### What problem was encountered?
Trying to transfer file from S3 to Azure using blob.upload it is taking long time for big files and also getting connection reset issue , because of that partial file is getting posted to azure blob storage

**Comment by rickle-msft** [comment]
@chhajerpawan Thank you for bringing this over from #373.

Can you please share some more information to help us diagnose? Why do you believe this issue is caused by the Storage SDK in particular? If you add threads, do you see your throughput increasing in direct proportion to the number of threads? Do you see network operations in other contexts achieving higher throughput? Are there any other workloads on your machine that could be taking up some of your bandwidth?

**Comment by chhajerpawan** [comment]
@rickle-msft 
I have used Azcopy and SDK both , using azcopy i am getting good performance for large file and using SDK i am not getting good performance. 

I my use case I am using multi threading approach but that is for files parallel processing, But I am here talking about a single large file upload. I am not getting good performance in single large file upload , upload performance i am getting about 6MB/s

**Comment by rickle-msft** [comment]
What throughput are you getting from azcopy?

**Comment by chhajerpawan** [comment]
about 50 to 80 MB/s

**Comment by rickle-msft** [comment]
Interesting. Can you give me some more information about the environment you're running in? Is this in a VM hosted in one of the cloud providers or local? What is your expected network bandwidth? Which version of Java are you using?

Additionally, are you blocked on this issue because there is some reason you cannot continue your work with azcopy alone?

**Comment by chhajerpawan** [comment]
We have a Java Based application using Java 8 and Deployed on Pivotal Cloud Foundry, This is a blocker for us as without good speed and connection reset issue fix we cannot go to production. 
Pivotal Cloud foundary is on premises private cloud where java based application is hosted. Application is using Azure Java Storage SDK version 8.0.0

**Comment by rickle-msft** [comment]
Thank you for those details. Can you please describe the conditions under which you see the connection reset issue? We have been seeing that with v10 periodically but have not seen much of that in v8.

**Comment by chhajerpawan** [comment]
When I tried to upload Large file >1 GB , Its not consistent, but many times i am getting error

**Comment by chhajerpawan** [comment]
Do we have a sample code where with V10.5.0 with proxy setting code base is working and able to upload /download file from azure blob storage

**Comment by rickle-msft** [comment]
Do you have any logs or request ids we can look through to try to find out more information about what may be going on?

**Comment by chhajerpawan** [comment]
2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR java.net.SocketException: Connection reset
   2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR     at java.net.SocketInputStream.read(SocketInputStream.java:210)
   2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR     at java.net.SocketInputStream.read(SocketInputStream.java:141)
   2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR     at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
   2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR     at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
   2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR     at sun.security.ssl.InputRecord.read(InputRecord.java:532)
   2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR     at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
   2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR     at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
   2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR     at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
   2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR     at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
   2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR     at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:198)
   2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR     at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
   2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR     at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
   2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR     at com.microsoft.azure.storage.core.Utility.writeToOutputStream(Utility.java:1389)
   2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR     at com.microsoft.azure.storage.core.Utility.writeToOutputStream(Utility.java:1290)
   2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR     at com.microsoft.azure.storage.blob.BlobOutputStreamInternal.write(BlobOutputStreamInternal.java:663)
   2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR     at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:800)

**Comment by rickle-msft** [comment]
Hi, @chhajerpawan. Sorry for the delay. Thank you for the stack trace! The SDK also supports SLF4J logging. Do you happen to have any logs that capture this error to give a little more context?

**Comment by chhajerpawan** [comment]
This is the error i am getting, Part from that there is no error i am getting, because in SDK every where is throws with exception 

2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR java.net.SocketException: Connection reset
2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR at java.net.SocketInputStream.read(SocketInputStream.java:210)
2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR at java.net.SocketInputStream.read(SocketInputStream.java:141)
2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR at sun.security.ssl.InputRecord.read(InputRecord.java:532)
2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:198)
2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR at com.microsoft.azure.storage.core.Utility.writeToOutputStream(Utility.java:1389)
2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR at com.microsoft.azure.storage.core.Utility.writeToOutputStream(Utility.java:1290)
2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR at com.microsoft.azure.storage.blob.BlobOutputStreamInternal.write(BlobOutputStreamInternal.java:663)
2019-03-14T11:39:25.15-0700 [APP/PROC/WEB/0] ERR at com.microsoft.azure.storage.blob.CloudBlockBlob.upload(CloudBlockBlob.java:800)

**Comment by rickle-msft** [comment]
@chhajerpawan Without more detailed logs, it is difficult for me to understand what behavior or usage pattern might be causing this. I do see that the stack trace originates in this SDK and understand that this is the only error you are getting, but I am unable to reproduce this error with the given information, so I cannot effectively debug the problem. If you are unable to provide logs, can you please describe in more detail the context around the operation you are doing? When I run our tests, and stress tests, I do not see this error or any performance issues, so there must be something specific to your environment going on.

**Comment by rickle-msft** [comment]
@chhajerpawan Alternatively, if you have code that you would willing to share here that we could use to reproduce the issue on our end, then I can try running things over here to dig into the details more.

**Comment by somanshreddy** [comment]
@chhajerpawan Based on the comments in #373, are you using the Input Stream returned by the S3 SDK? And what version of the S3 SDK is this?
