### ISSUE TITLE
Not able to get blob in Asynchronous call

### ISSUE THREAD

**Issue by sagarpatel07** [Azure/azure-storage-java#455]
### Which service(blob, file, queue, table) does this issue concern?
Azure Blob

### Which version of the SDK was used?
SDK V10

### What problem was encountered?
Not able to get blob while using Asynchronous call but when i set blockingGet(); code is able to get list of blob available on azure sever.

### Have you found a mitigation/solution?
No, it is working fine in SDK8 but not working in SDK10 and may be root cause is Asynchronous call.

Please find below code which i am have used.
Asynchronous Code - this code is not returning any blob or any error:

static void listBlobs(ContainerURL containerURL) {

		ListBlobsOptions options = new ListBlobsOptions();

		options.withMaxResults(10);

		containerURL.listBlobsFlatSegment(null, options, null)
				.flatMap(containerListBlobFlatSegmentResponse -> listAllBlobs(containerURL,
						containerListBlobFlatSegmentResponse));
				
	}

	private static Single<ContainerListBlobFlatSegmentResponse> listAllBlobs(ContainerURL url,
			ContainerListBlobFlatSegmentResponse response) {
		if (response.body().segment() != null) {
			for (BlobItem b : response.body().segment().blobItems()) {

				String output = "Blob name: " + b.name();
				if (b.snapshot() != null) {
					output += ", Snapshot: " + b.snapshot();
				}
				System.out.println(output);
			}
		} else {
			System.out.println("There are no more blobs to list off.");
		}

		if (response.body().nextMarker() == null) {
			return Single.just(response);
		} else {

			String nextMarker = response.body().nextMarker();

			return url.listBlobsFlatSegment(nextMarker, new ListBlobsOptions().withMaxResults(10), null).flatMap(
					containersListBlobFlatSegmentResponse -> listAllBlobs(url, containersListBlobFlatSegmentResponse));
		}
	}
Code with blockingGet() method - this is returning 4 blobs which are available on azure

static void listBlobs(ContainerURL containerURL) {

		ListBlobsOptions options = new ListBlobsOptions();

		options.withMaxResults(10);

		containerURL.listBlobsFlatSegment(null, options, null)
				.flatMap(containerListBlobFlatSegmentResponse -> listAllBlobs(containerURL,
						containerListBlobFlatSegmentResponse))
				.blockingGet();
	}

	private static Single<ContainerListBlobFlatSegmentResponse> listAllBlobs(ContainerURL url,
			ContainerListBlobFlatSegmentResponse response) {
		if (response.body().segment() != null) {
			for (BlobItem b : response.body().segment().blobItems()) {

				String output = "Blob name: " + b.name();
				if (b.snapshot() != null) {
					output += ", Snapshot: " + b.snapshot();
				}
				System.out.println(output);
			}
		} else {
			System.out.println("There are no more blobs to list off.");
		}

		if (response.body().nextMarker() == null) {
			return Single.just(response);
		} else {

			String nextMarker = response.body().nextMarker();

			return url.listBlobsFlatSegment(nextMarker, new ListBlobsOptions().withMaxResults(10), null).flatMap(
					containersListBlobFlatSegmentResponse -> listAllBlobs(url, containersListBlobFlatSegmentResponse));
		}
	}

Please help.
Thanks in advance :)

**Comment by rickle-msft** [comment]
Hi, @sagarpatel07. Thank you for asking this question! Rx (the asynchronous framework) is a little unique in that the method calls themselves do not kick off the operation. You have to call one of the overloads for [subscribe](http://reactivex.io/RxJava/javadoc/io/reactivex/Single.html#subscribe-io.reactivex.functions.Consumer-io.reactivex.functions.Consumer-) in order for the network call to happen, which I don't see in the first code block. Swapping out blockingGet for subscribe will actually make the request happen. Just be aware that it then becomes non blocking, so the method may still not return anything. Instead the result will be processed by the "flow" established by listAllBlobs (I am happy to explain this more if it does not make sense). Please let me know if you have any more issues or questions!

And if I may ask for the purposes of improving our own documentation, where did you look to find an answer to this? Is there a particular place where if we had provided this information or some guidance on Rx you would have been able to resolve this independently? Or did you come straight to github for help?

**Comment by sagarpatel07** [comment]
Hi @rickle-msft .
Thanks for your response. I have added subscribe method but still Rx is not able to get blob.
I have follow below documents:
[Azure Document](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-java-v10) - this document code is containing so many errors and some break link as well.
[Azure git hub document](https://github.com/Azure-Samples/storage-blobs-java-v10-quickstart) - i have used this code but still Rx is not working.

I have one more question -  Please let me know if there is any way in SDK 10 that i can directly get content of file (as input stream ) without downloading file on local system.

PS: i am able to get blbo using SDK 8.

**Comment by rickle-msft** [comment]
@sagarpatel07 I have a couple questions about the situation:
1. You are mentioning trouble with a get blob/download() call, but the code snippets you've shared only contain listing APIs. Am I missing something? Or where do you actually make the download calls?
2. What is the context for these apis in your code? Does the program exit after the download call? Or is there other logic and then termination? Or is there some sort of user interface that keeps the program alive until a user exits the program explicitly?

As for your other question, are you asking if there is a way to get an input stream to a blob instead of a Flowable?

**Comment by sagarpatel07** [comment]
@rickle-msft Thanks for your reply.
please  find below answer to your question:

>You are mentioning trouble with a get blob/download() call, but the code snippets you've shared only contain listing APIs. Am I missing something? Or where do you actually make the download calls?

Yes, I am facing issue with download as well. but currently i am trying to just list blob using Rx as facing issue with download blob.

> What is the context for these apis in your code? Does the program exit after the download call? Or is there other logic and then termination? Or is there some sort of user interface that keeps the program alive until a user exits the program explicitly?

I have simple java program, which i have copied from [here](https://github.com/Azure-Samples/storage-blobs-java-v10-quickstart/blob/master/src/main/java/quickstart/Quickstart.java) but i have modified code and removed user input from command line section.

> As for your other question, are you asking if there is a way to get an input stream to a blob instead of a Flowable?

Yes, I require content of file as input stream as i am using input stream for Apache Tika.

Please find below my whole code:

`
public class Test2 {
	static void listBlobs(ContainerURL containerURL) {

		ListBlobsOptions options = new ListBlobsOptions();

		options.withMaxResults(10);

		containerURL.listBlobsFlatSegment(null, options, null)
				.flatMap(containerListBlobFlatSegmentResponse -> listAllBlobs(containerURL,
						containerListBlobFlatSegmentResponse))
				.subscribe(response -> {
					System.out.println("Completed list blobs request.");
					System.out.println(response.statusCode());
				});
	}

	private static Single<ContainerListBlobFlatSegmentResponse> listAllBlobs(ContainerURL url,
			ContainerListBlobFlatSegmentResponse response) {
		if (response.body().segment() != null) {
			for (BlobItem b : response.body().segment().blobItems()) {

				String output = "Blob name: " + b.name();
				if (b.snapshot() != null) {
					output += ", Snapshot: " + b.snapshot();
				}
				System.out.println(output);
			}
		} else {
			System.out.println("There are no more blobs to list off.");
		}

		if (response.body().nextMarker() == null) {
			return Single.just(response);
		} else {

			String nextMarker = response.body().nextMarker();

			return url.listBlobsFlatSegment(nextMarker, new ListBlobsOptions().withMaxResults(10), null).flatMap(
					containersListBlobFlatSegmentResponse -> listAllBlobs(url, containersListBlobFlatSegmentResponse));
		}
	}

	public static void main(String[] args) throws java.lang.Exception {
		ContainerURL containerURL;

		String accountName = "accountname";
		String accountKey = "accountkey";

		SharedKeyCredentials creds = new SharedKeyCredentials(accountName, accountKey);

		final ServiceURL serviceURL = new ServiceURL(new URL("https://" + accountName + ".blob.core.windows.net"),
				StorageURL.createPipeline(creds, new PipelineOptions()));
		containerURL = serviceURL.createContainerURL("demo");

		try {
			ContainerCreateResponse response = containerURL.create(null, null, null).blockingGet();
			System.out.println("Container Create Response was " + response.statusCode());
		} catch (RestException e) {
			if (e instanceof RestException && ((RestException) e).response().statusCode() != 409) {
				throw e;
			} else {
				System.out.println("quickstart container already exists, resuming...");
			}
		}
		System.out.println("Listing blobs in the container: " + containerURL);
		listBlobs(containerURL);
	}
}
`

**Comment by rickle-msft** [comment]
I see. Thank you for that information. Can you try adding at the very end of your program either a Thread.sleep() for like five seconds or a System.in.readline(). I believe the reason why you are not seeing the blobs listed is that the program is terminating before the asynchronous operation finishes and prints anything, cancelling the operation. Since listBlobs is now sync/blocking, the program simply runs to completion. 

As of right now, the v10+ SDK does not offer a way to get an input stream to a blob (v8 does offer this functionality, and it should be possible to load them together, but v8 is entirely synchronous). The reason this is not offered is because there is not support for async InputStreams, so offering such a feature breaks the async paradigm of v10+. That said, we have seen this request numerous times and are working on a good way to offer this functionality in a way that still fits with the new design.

**Comment by sagarpatel07** [comment]
@rickle-msft Thanks for information.
I have added Thread.sleep(5000); in code and able to list blobs using Rx call. but unfortunately i need to go with SDK 8 as i required blob as input stream.

Thanks for providing clarification and helping me out.

**Comment by rickle-msft** [comment]
Sure thing! If you need any support with v8, let us know, and if you are at all interested, you can keep an eye out for when we address that scenario in v11+ in case you have any desire to migrate there. 

I'll close this issue now as I think any questions have been resolved and you are unblocked, but please feel free to reopen it should have further issues or questions.

**Comment by kalyansagi** [comment]
@rickle-msft I'm not able to instantiate the ListBlobsOptions in my class. The same instance works fine in local but not in pcf after deploying on the cloud. 
See the approach below:
public void listBlobs() {
        System.out.println("Before Initializing ListBlobsOptions");
        **ListBlobsOptions listBlobsOptions = new ListBlobsOptions();**
        containerURL.listBlobsFlatSegment(null, listBlobsOptions.withMaxResults(10), null).flatMap(containerListBlobFlatSegmentResponse ->
                listAllBlobs(containerURL, containerListBlobFlatSegmentResponse))
                .subscribe(response-> {
                    System.out.println("Completed list blobs request.");
                    System.out.println(response.statusCode());
                });
    }

**Error logs:**
```at java.lang.Thread.run(Thread.java:748) [na:1.8.0_202]
   2019-08-07T15:15:22.22-0400 [RTR/8] OUT mapgenerator.apps.pp01.useast.cf.ford.com - [2019-08-07T19:15:22.175+0000] "GET /api/v1/downloadTiles HTTP/1.1" 500 0 302 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36" "10.224.32.35:32828" "10.224.32.109:61058" x_forwarded_for:"136.2.17.160, 10.224.32.35" x_forwarded_proto:"https" vcap_request_id:"a0490649-6901-4943-793e-adde2bbe2c48" response_time:0.053182431 app_id:"45020c95-1730-4f21-8f97-7fa0cc67c7ff" app_index:"0" x_b3_traceid:"7969216829b7dbdc" x_b3_spanid:"7969216829b7dbdc" x_b3_parentspanid:"-"
   2019-08-07T15:15:22.22-0400 [RTR/8] OUT 
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] OUT Before Initializing ListBlobsOptions
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR [ERROR] ExceptionLoggingFilter - Uncaught exception thrown <org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.azure.storage.blob.ListBlobsOptions>org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.azure.storage.blob.ListBlobsOptions
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1006)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.springframework.cloud.sleuth.instrument.web.ExceptionLoggingFilter.doFilter(ExceptionLoggingFilter.java:48)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at brave.servlet.TracingFilter.doFilter(TracingFilter.java:86)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.cloudfoundry.router.ClientCertificateMapper.doFilter(ClientCertificateMapper.java:77)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at java.lang.Thread.run(Thread.java:748)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.azure.storage.blob.ListBlobsOptions
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at com.ford.cbz.map.generator.MapGenerator.listBlobs(MapGenerator.java:67)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at com.ford.cbz.map.generator.MapController.getBlob(MapController.java:18)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at java.lang.reflect.Method.invoke(Method.java:498)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
   2019-08-07T15:16:23.50-0400 [APP/PROC/WEB/0] ERR     ... 53 more```

**Comment by kalyansagi** [comment]
@rickle-msft Never mind. I was able to get this through by changing the storage dependency. This page helped. Thank you!
