### ISSUE TITLE
Issue with CloudStorageAccount when using com.microsoft.azure:azure-storage-blob:11.0.0 

### ISSUE THREAD

**Issue by kalyansagi** [Azure/azure-storage-java#487]
### Which service(blob, file, queue, table) does this issue concern?
I have started facing an issue with ListBlobsOptions where the instance was not being instantiated in PCF even though it does work in local. After reading through the github pages, I found com.microsoft.azure:azure-storage-blob:11.0.0 has fixed the issue. But now after upgrading the blob storage, I'm facing a new issue with CloudStorageAccount. 

### Which version of the SDK was used?
Please note that if your issue is with v11, we are recommending customers either move back to v11 or move to v12 (currently in preview) if at all possible. Hopefully this resolves your issue, but if there is some reason why moving away from v11 is not possible at this time, please do continue to ask your question and we will do our best to support you. The README for this SDK has been updated to point to more information on why we have made this decision. 
V11

### What problem was encountered?
rg.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mapController': Unsatisfied dependency expressed through field 'mapGenerator'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mapGenerator' defined in file [/Users/storm/IdeaProjects/STORM-CBZ/components/map-generator/build/classes/java/main/com/ford/cbz/map/generator/MapGenerator.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'CloudStorageAccount' defined in class path resource [com/ford/cbz/map/generator/config/MapGeneratorConfig.class]: Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.microsoft.azure.storage.CloudStorageAccount] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@368239c8]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:587) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:91) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:373) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1350) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:580) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869) ~[spring-context-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at com.ford.cbz.map.MapGeneratorApp.main(MapGeneratorApp.java:15) ~[main/:na]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mapGenerator' defined in file [/Users/storm/IdeaProjects/STORM-CBZ/components/map-generator/build/classes/java/main/com/ford/cbz/map/generator/MapGenerator.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'CloudStorageAccount' defined in class path resource [com/ford/cbz/map/generator/config/MapGeneratorConfig.class]: Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.microsoft.azure.storage.CloudStorageAccount] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@368239c8]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:732) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:197) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1276) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1133) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1065) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:584) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	... 19 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'CloudStorageAccount' defined in class path resource [com/ford/cbz/map/generator/config/MapGeneratorConfig.class]: Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.microsoft.azure.storage.CloudStorageAccount] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@368239c8]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:558) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1065) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:818) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:724) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	... 32 common frames omitted
Caused by: java.lang.IllegalStateException: Failed to introspect Class [com.microsoft.azure.storage.CloudStorageAccount] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@368239c8]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:680) ~[spring-core-5.1.0.RELEASE.jar:5.1.0.RELEASE]
	at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:540) ~[spring-core-5.1.0.RELEASE.jar:5.1.0.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.buildLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:207) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.findLifecycleMetadata(InitDestroyAnnotationBeanPostProcessor.java:188) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(InitDestroyAnnotationBeanPostProcessor.java:127) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessMergedBeanDefinition(CommonAnnotationBeanPostProcessor.java:297) ~[spring-context-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyMergedBeanDefinitionPostProcessors(AbstractAutowireCapableBeanFactory.java:1022) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	... 42 common frames omitted
Caused by: java.lang.SecurityException: class "com.microsoft.azure.storage.blob.CloudBlobClient"'s signer information does not match signer information of other classes in the same package
	at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1150) ~[na:na]
	at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:905) ~[na:na]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1014) ~[na:na]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623) ~[na:na]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3167) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2310) ~[na:na]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:662) ~[spring-core-5.1.0.RELEASE.jar:5.1.0.RELEASE]
	... 49 common frames omitted

### Have you found a mitigation/solution?
Not yet

**Comment by rickle-msft** [comment]
Hi, @kalyansagi. Thank you for posting this issue. Just to confirm my understanding, you were experiencing issues instantiating ListBlobsOptions in v8 but found it was resolved in v11 and now you're seeing a similar issue with a different type in v11?

**Comment by kalyansagi** [comment]
That is correct.

**Comment by kalyansagi** [comment]
@rickle-msft Do you have any updates on this? This seems to be an issue only with V11.0.0

**Comment by rickle-msft** [comment]
Sorry for the delay. I must've missed the notification for your response. 

Taking a look at the initial post again, it looks like you're trying to instantiate a CloudStorageAccount in v11? Is that correct? This type no longer exists in v11, which might explain why spring can't work with it.

**Comment by kalyansagi** [comment]
yes, initially I was using 10.0.1 which works fine w.r.t CloudStorageAccount but ListBlobsOptions doesn't instantiate. So, I had to update to 11.0.0 as suggested in another thread here. And now 11.0.0 fails on CloudStorageAccount. Any thoughts on how to get this working?

**Comment by rickle-msft** [comment]
Apologies if this line of questioning feels tedious; I'm still trying to gather information about the symptoms and don't have a ton of experience with spring to begin with.

I'm surprised that you could instantiate CloudStorageAccount in 10.0.1 because there hasn't been anything CloudX since 10.0.0. In any case, I think the best I can recommend is converting from CloudStorageAccount to the rough equivalent in v10/11 which is the ServiceURL type. 

If at all possible, I'd recommend staying on v8 altogether, but if you need to stay on v10/11, that'd be my next suggestion.

**Comment by kalyansagi** [comment]
I tried V8 as well but BlockBlobURL& ContainerURL available where I need them in my case.

**Comment by rickle-msft** [comment]
It sounds like you're kind of straddling two versions here. CloudStorageAccount, CloudBlobContainer, CloudBlob, etc. are in v8 whereas ServiceURL, ContainerURL, BlobURL, etc. are in v10/11. If you've got some combination that transgresses the upgrade boundary, you're going to have problems one way or the other and the first step would be refactoring to use exclusively one version.

**Comment by kalyansagi** [comment]
Thank you @rickle-msft I'll refactor the dependencies accordingly.

**Comment by rickle-msft** [comment]
I am going to close this issue as I believe it has been resolved, but please feel free to reopen it or continue to otherwise engage if you need further support.

**Comment by kalyansagi** [comment]
@rickle-msft  I am looking at a way to upload a ".db" file from my local machine to Azure Blob Storage. I don't seem to get to the right documentation as I am not very familiar with Azure Ecosystem. Can you please point me in the right direction?   Sorry to use this thread to post my question.

**Comment by rickle-msft** [comment]
@kalyansagi No worries. You are welcome to use whichever channel makes sense to you :) It looks to me like v11 docs were taken down, which I was not aware of and may be part of the transition to v12. I'm checking over here to see if that was intentional. In the meantime, I can point you to TransferManager.uploadFile. This should be a quick and simple way to get your .db (or any extension) file up into Azure. If you have any difficulty with this method, please continue to reach out.

**Comment by kalyansagi** [comment]
I did see TransferManager.uploadFile() in the docs but not very clear with the implementation. Can you give me a sample/example ?? Assuming I have my file (.db) in location directory "/Users/kalyansagi/IdeaProjects/memory:db1.db" 
I appreciate your help!

**Comment by rickle-msft** [comment]
[Here](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/microsoft-azure-storage-blob/src/test/java/com/microsoft/azure/storage/Samples.java#L1455) is a sample using the file transfer methods. It may be a little obfuscated by the use of reactive types, so [here](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/microsoft-azure-storage-blob/src/test/java/com/microsoft/azure/storage/TransferManagerTest.groovy#L46) is our basic test exercising the method that may help supplement what you're seeing.

For completeness, [here](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/microsoft-azure-storage-blob/src/main/java/com/microsoft/azure/storage/blob/TransferManager.java#L70) is the method itself. 

Essentially you should just be able to open an AsynchronousFileChannel to the path you specified and pass that along with some other (mostly optional) parameters and then block on the return value and that's about it. 

Please let me know if you have further questions.

**Comment by kalyansagi** [comment]
I was able to get piece working. I will let you know if any help needed. Thanks as always!!
